name       : perl-test-pod-coverage
version    : '1.10'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/N/NE/NEILB/Test-Pod-Coverage-1.10.tar.gz : 48c9cca9f7d99eee741176445b431adf09c029e1aa57c4703c9f46f7601d40d4
license    : Artistic-2.0
component  : programming.perl
summary    : Test::Pod::Coverage - Check for pod coverage in your distribution.
description: |
    This module is used to add a test to your Perl distribution, which checks for pod coverage of all appropriate files.
builddeps  :
    - perl-devel-symdump
    - perl-pod-coverage
    - perl-test-pod
rundeps    :
    - perl-devel-symdump
    - perl-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
